### ISSUE TITLE
the /buy command is not doing anything

### ISSUE THREAD

**Issue by stsguitar23** [CraftingStore/Suggestions#115]
Store is completely set up, and responds to the test sent by the website. However when I type /buy (I am OP'd) it throws an error in the console and does nothing. I have created packages and categories, and they are all enabled.

**To Reproduce**
All I did was install the program as directed, and attempt to use /buy

**Expected behavior**
Was hoping the store interface would pop up

**Screenshots**
no screenshot but here's the error

[WARNING] [CraftingStore] Plugin CraftingStore v2.0.4 generated an exception while executing task 176603

java.lang.NullPointerException: null

at net.craftingstore.bukkit.inventory.InventoryBuilder.buildInventory(InventoryBuilder.java:23) ~[?:?]

at net.craftingstore.bukkit.inventory.InventoryBuilder.buildInventory(InventoryBuilder.java:19) ~[?:?]

at net.craftingstore.bukkit.commands.BuyCommand.lambda$onCommand$0(BuyCommand.java:38) ~[?:?]

at net.craftingstore.bukkit.commands.BuyCommand$$Lambda$2693.000000003D7E6A80.run(Unknown Source) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192] 

**Platform**
spigot minecraft latest version as of 1/28/19

**Comment by Tim-NL** [comment]
Hi, 

Can you please share your store URL, or create a support ticket at CraftingStore.net and reference this issue ID in there. 
We need to do some tests on the API endpoint for your webshop. 

-Tim

**Comment by Tim-NL** [comment]
I didn't get any response. I'll close the issue. Please create a support ticket with the requested information. 

-Tim
