### ISSUE TITLE
Stack trace generated randomly in console

### ISSUE THREAD

**Issue by Ultracrepadarian** [CraftingStore/Suggestions#202]
My issue is that there is a random stack trace that is generated in the console. The stack trace is as follows:

`[15:03:20 WARN]: java.net.SocketTimeoutException: Read timed out
[15:03:20 WARN]:        at java.net.SocketInputStream.socketRead0(Native Method)
[15:03:20 WARN]:        at java.net.SocketInputStream.socketRead(Unknown Source)
[15:03:20 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[15:03:20 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[15:03:20 WARN]:        at sun.security.ssl.InputRecord.readFully(Unknown Source)
[15:03:20 WARN]:        at sun.security.ssl.InputRecord.read(Unknown Source)
[15:03:20 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[15:03:20 WARN]:        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
[15:03:20 WARN]:        at sun.security.ssl.AppInputStream.read(Unknown Source)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
[15:03:20 WARN]:        at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
[15:03:20 WARN]:        at net.craftingstore.core.http.CraftingStoreAPIImpl.lambda$getGUI$8(CraftingStoreAPIImpl.java:135)
[15:03:20 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:03:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:03:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:03:20 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:03:20 WARN]: java.util.concurrent.ExecutionException: net.craftingstore.core.exceptions.CraftingStoreApiException: Inventory call failed
[15:03:20 WARN]:        at java.util.concurrent.FutureTask.report(Unknown Source)
[15:03:20 WARN]:        at java.util.concurrent.FutureTask.get(Unknown Source)
[15:03:20 WARN]:        at net.craftingstore.core.http.CraftingStoreCachedAPI.refreshGUICache(CraftingStoreCachedAPI.java:55)
[15:03:20 WARN]:        at net.craftingstore.core.scheduler.InventoryRenewer.run(InventoryRenewer.java:28)
[15:03:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[15:03:20 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[15:03:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:03:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:03:20 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:03:20 WARN]: Caused by: net.craftingstore.core.exceptions.CraftingStoreApiException: Inventory call failed
[15:03:20 WARN]:        at net.craftingstore.core.http.CraftingStoreAPIImpl.lambda$getGUI$8(CraftingStoreAPIImpl.java:137)
[15:03:20 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:03:20 WARN]:        ... 3 more`

**Comment by Tim-NL** [comment]
Hello,

Can you please create a support ticket from the account that has this issue? It might be an isolated incident within the account.

https://craftingstore.net/admin/support

~Tim
