### ISSUE TITLE
javax.net.ssl.SSLException probably due to Java version 14

### ISSUE THREAD

**Issue by bobhenl** [CraftingStore/Suggestions#461]
**Describe the bug**
Hi, I have this error in console while server is loading (only on one of three servers), but test broadcast worked.
![image](https://user-images.githubusercontent.com/18662086/100992999-1ffb7e80-3555-11eb-82f3-cda45a34e38f.png)

**To Reproduce**
1. Try use Java 14.
2. Connect server to CraftingStore.

**Expected behavior**
Any error on startup.

**Error log**
https://pastebin.com/cEEeTYMa

**Platform**
![image](https://user-images.githubusercontent.com/18662086/100993175-5d600c00-3555-11eb-92db-72fa13be5d8b.png)
Minecraft plugin issue

**Comment by bobhenl** [comment]
On bungee with Java 14 too

```
[04:40:32] [pool-12-thread-1/ERROR]: javax.net.ssl.SSLException: Connection reset
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1654)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
[04:40:32] [pool-12-thread-1/ERROR]: 	at net.craftingstore.core.http.CraftingStoreAPIImpl.lambda$getDonationQueue$4(CraftingStoreAPIImpl.java:92)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[04:40:32] [pool-12-thread-1/ERROR]: 	Suppressed: java.net.SocketException: Broken pipe
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1052)
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82)
[04:40:32] [pool-12-thread-1/ERROR]: 		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:355)
[04:40:32] [pool-12-thread-1/ERROR]: 		... 29 more
[04:40:32] [pool-12-thread-1/ERROR]: Caused by: java.net.SocketException: Connection reset
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:982)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1411)
[04:40:32] [pool-12-thread-1/ERROR]: 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1022)
[04:40:32] [pool-12-thread-1/ERROR]: 	... 25 more
[04:40:32] [CraftingStore Pool Thread #1/ERROR] [CraftingStore]: Failed to check for donations. If this issue persists, please contact support at https://craftingstore.net.
```

**Comment by Tim-NL** [comment]
Hi,

We are unable to reproduce the issue using Java 14, we've been testing this for hours, and no errors popped up. Even when changing the endpoint, it did not work. 

We are working on checking what is going on here, but we think that the issue is caused by the servers themselves, and not on our side at this point in time.

-Tim
